ClearMeasureLabs/onion-architecture-dotnet-7-container-apps

azure-pipelines.yml
=> Update octo gitref

.octopus/deployment_process.ocl, .octopus/variables.ocl, azure-pipelines.yml
=> Automate az resources

src/UI/Client/Pages/Index.razor
=> updated hello text

.octopus/deployment_process.ocl, .octopus/variables.ocl, src/UI/Server/CallHealthCheckEndpoint.ps1
=> Connect db

.octopus/deployment_process.ocl, .octopus/variables.ocl, azure-pipelines.yml, src/Database/DatabaseARM.json, src/Database/DatabaseARMParameters.json
=> Create higher env resources

.octopus/deployment_process.ocl, .octopus/variables.ocl, azure-pipelines.yml
=> Update deploy for portability

.octopus/deployment_process.ocl, .octopus/variables.ocl
=> Make dbservername unique

.octopus/deployment_process.ocl
=> Remove community step templates

.octopus/deployment_process.ocl, .octopus/variables.ocl
=> Update env slugs

azure-pipelines.yml
=> updated octo steps to use vars

.octopus/deployment_process.ocl, .octopus/variables.ocl
=> Retrieve azure vars

README.md
=> Update gha getting started

.github/workflows/dotnet.yml, .octopus/variables.ocl
=> updated gha versioning

.teamcity/pom.xml, .teamcity/settings.kts
=> added teamcity config as code

.teamcity/settings.kts
=> updated teamcity config

azure-pipelines.yml, build.ps1, src/AcceptanceTests/AcceptanceTests.csproj, src/AcceptanceTests/Counter/CounterIncrementsTester.cs
=> Update private build

.github/workflows/dotnet.yml
=> updated gha workflow to use cli deploy action

.github/workflows/dotnet.yml, .teamcity/settings.kts
=> updated gha and tc build scripts for private build

.octopus/deployment_process.ocl, .octopus/variables.ocl
=> removed ensureenvironmentsexist TDD value

README.md
=> Add healthcheck monitoring

.octopus/deployment_process.ocl
=> corrected content url

.teamcity/settings.kts, src/AcceptanceTests/AcceptanceTests.csproj
=> Update tc chromedriver
